name:                dovetail
version:             0.1.0.0
github:              "paf31/dovetail"
license:             BSD3
author:              "Phil Freeman"
maintainer:          "freeman.phil@gmail.com"
copyright:           "2021 Phil Freeman"

extra-source-files:
- README.md

description:         Dovetail is a general-purpose PureScript corefn interpreter with an FFI to Haskell. 
                     Please see the README on GitHub at <https://github.com/paf31/dovetail#readme>, or 
                     check out the examples directory, to learn how to use the library.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Werror
  - -fwarn-unused-imports
  dependencies:
  - aeson
  - containers
  - mtl
  - purescript
  - purescript-cst
  - scientific
  - semialign
  - text
  - these
  - transformers
  - unordered-containers
  - vector

executables:
  query-json:
    main:                Main.hs
    source-dirs:         examples/query-json
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -fwarn-unused-imports
    dependencies:
    - dovetail
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - mtl
    - purescript
    - purescript-cst
    - text
    - transformers
    - vector
    
  fake-data:
    main:                Main.hs
    source-dirs:         examples/fake-data
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -fwarn-unused-imports
    dependencies:
    - dovetail
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - mtl
    - purescript
    - purescript-cst
    - random
    - text
    - transformers
    - vector
    
tests:
  dovetail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - directory
    - dovetail
    - filepath
    - hspec
    - hspec-golden
    - purescript
    - QuickCheck
    - generic-arbitrary
    - quickcheck-instances
    - text
