name:                dovetail
version:             0.1.1.0
github:              "paf31/dovetail"
license:             BSD3
license-file:        LICENSE
author:              "Phil Freeman"
maintainer:          "freeman.phil@gmail.com"
copyright:           "2021 Phil Freeman"
category:            Language
synopsis:            A PureScript interpreter with a Haskell FFI.
description:         Dovetail is a general-purpose PureScript corefn interpreter with an FFI to Haskell. 
                     Please see the README on GitHub at <https://github.com/paf31/dovetail#readme>, or 
                     check out the examples directory, to learn how to use the library.

extra-source-files:  README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-unused-imports
  dependencies:
  - ansi-terminal
  - containers
  - exceptions
  - hashable
  - haskeline
  - mtl
  - purescript
  - purescript-cst
  - semialign
  - text
  - these
  - transformers
  - unordered-containers
  - vector
    
tests:
  dovetail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - directory
    - dovetail
    - filepath
    - hspec
    - hspec-golden
    - purescript
    - QuickCheck
    - generic-arbitrary
    - quickcheck-instances
    - text
    - vector
